import fs from "fs";
import path from "path";

// const fs = require("fs");
// const path = require("path");

function deleteFolder(folder) {
  if (!fs.existsSync(folder)) return;
  const files = fs.readdirSync(folder);
  files.forEach((file) => {
    const curPath = path.join(folder, file);
    if (fs.lstatSync(curPath).isDirectory()) {
      deleteFolder(curPath);
    } else {
      fs.unlinkSync(curPath);
    }
  });
}

function writeFile(file, content) {
  const filePath = path.resolve(file);
  const dirPath = path.dirname(filePath);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    console.log(`Directory ${dirPath} created.`);
  } else {
    console.log(`Directory ${dirPath} already exists.`);
  }
  fs.writeFileSync(filePath, content, "utf8");
}

const config = {
  templates: {
    default: {
      outputSourceFiles: true,
      theme: "default",
      layoutFile: "layout.tmpl",
    },
  },
};
// A
writeFile("./jsdoc/config/a/conf.json", JSON.stringify(config));
writeFile(
  "./jsdoc/config/a/layout.tmpl",
  `
<?js /*
    Copyright 2011 the JSDoc Authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: <?js= title ?></title>

    <script src="scripts/prettify.js"> </script>
    <script src="scripts/lang-css.js"> </script>
    <link type="text/css" rel="stylesheet" href="styles/tomorrow.min.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">This is A template</h1>

    <?js= content ?>
</div>

<nav>
    <?js= this.nav ?>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc <?js= env.version.number ?></a><?js if(env.conf.templates && env.conf.templates.default && env.conf.templates.default.includeDate !== false) { ?> on <?js= (new Date()) ?><?js } ?>
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
  `
);

// B
writeFile("./jsdoc/config/b/conf.json", JSON.stringify(config));
writeFile(
  "./jsdoc/config/b/layout.tmpl",
  `
<?js /*
    Copyright 2011 the JSDoc Authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: <?js= title ?></title>

    <script src="scripts/prettify.js"> </script>
    <script src="scripts/lang-css.js"> </script>
    <link type="text/css" rel="stylesheet" href="styles/tomorrow.min.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">This is B template</h1>

    <?js= content ?>
</div>

<nav>
    <?js= this.nav ?>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc <?js= env.version.number ?></a><?js if(env.conf.templates && env.conf.templates.default && env.conf.templates.default.includeDate !== false) { ?> on <?js= (new Date()) ?><?js } ?>
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
  `
);

// U
writeFile("./jsdoc/config/u/conf.json", JSON.stringify(config));
writeFile(
  "./jsdoc/config/u/layout.tmpl",
  `
<?js /*
    Copyright 2011 the JSDoc Authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: <?js= title ?></title>

    <script src="scripts/prettify.js"> </script>
    <script src="scripts/lang-css.js"> </script>
    <link type="text/css" rel="stylesheet" href="styles/tomorrow.min.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">This is U template</h1>

    <?js= content ?>
</div>

<nav>
    <?js= this.nav ?>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc <?js= env.version.number ?></a><?js if(env.conf.templates && env.conf.templates.default && env.conf.templates.default.includeDate !== false) { ?> on <?js= (new Date()) ?><?js } ?>
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
  `
);

// doc index
writeFile("./jsdoc/doc/readme.md", "# Documentation generated by JSDoc 4.0.4");
writeFile(
  "./jsdoc/doc/index.html",
  `
  <!DOCTYPE html>
  <html lang="en">
    <body>
      <script>
        window.location.href = "./A/index.html";
      </script>
    </body>
  </html>
  `
);
